<?php
$title = 'Edit product';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php $form = $this->form; ?>
<?php $form->setAttribute('action', $this->url('product', array('action' => 'edit', 'id' => $this->id))); ?>
<?php $form->setAttribute('role', 'form'); ?>
<?php $form->prepare();?>
<?= $this->form()->openTag($form); ?>
<?= $this->formHidden($form->get('id')); ?>
<div class="form-group">
    <?= $this->formLabel($form->get('title')); ?>
    <?= $this->formInput($form->get('title')); ?>
</div>
<div class="form-group">
    <?= $this->formLabel($form->get('description')); ?>
    <?= $this->formInput($form->get('description')); ?>
</div>
<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
